HOST = ENV['HOST']
SESSION_SECRET = ENV['SECRET_KEY'] || 'aaaaa'
TOKEN_URL = ENV['TOKEN_URL'] || '/token'

REDIS_URI = ENV['REDISTOGO_URI'] || ENV['REDIS_URI']

ADN_ID = ENV['ADN_ID']
ADN_SECRET = ENV['ADN_SECRET']
ADN_TOKEN = ENV['ADN_TOKEN']

SUPERFEEDR_LOGIN = ENV['SUPERFEEDR_LOGIN']
SUPERFEEDR_PASSWORD = ENV['SUPERFEEDR_PASSWORD']
